kdeinit5: preparing to launch '/usr/lib/kf5/klauncher'
kdeinit5: Launched KLauncher, pid = 592, result = 0
kdeinit5: opened connection to :0
kdeinit5: Got SETENV 'XCURSOR_THEME=GoVi-Cu' from launcher.
kdeinit5: Got SETENV 'XCURSOR_SIZE=24' from launcher.
kdeinit5: Got SETENV 'GTK_RC_FILES=/etc/gtk/gtkrc:/home/govi/.gtkrc:/home/govi/.config/gtkrc' from launcher.
kdeinit5: Got SETENV 'GTK2_RC_FILES=/etc/gtk-2.0/gtkrc:/home/govi/.gtkrc-2.0:/home/govi/.config/gtkrc-2.0' from launcher.
kdeinit5: Got SETENV 'SESSION_MANAGER=local/GoVi-PC:@/tmp/.ICE-unix/648,unix/GoVi-PC:/tmp/.ICE-unix/648' from launcher.
kdeinit5: Got SETENV 'SESSION_MANAGER=local/GoVi-PC:@/tmp/.ICE-unix/648,unix/GoVi-PC:/tmp/.ICE-unix/648' from launcher.
imwheel: no process found
INFO: imwheel started (pid=881)
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/desktop.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/desktop.so'
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/file.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/file.so'
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/file.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/file.so'
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/file.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/file.so'
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/file.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/file.so'
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/file.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/file.so'
kdeinit5: PID 1251 terminated.
kdeinit5: PID 1069 terminated.
kdeinit5: PID 1262 terminated.
kdeinit5: PID 1039 terminated.

###!!! [Parent][RunMessage] Error: Channel closing: too late to send/recv, messages will be lost


###!!! [Parent][RunMessage] Error: Channel closing: too late to send/recv, messages will be lost


###!!! [Parent][RunMessage] Error: Channel closing: too late to send/recv, messages will be lost


###!!! [Parent][RunMessage] Error: Channel closing: too late to send/recv, messages will be lost


###!!! [Parent][RunMessage] Error: Channel closing: too late to send/recv, messages will be lost

kdeinit5: Got EXEC_NEW 'onboard' from launcher.
kdeinit5: preparing to launch 'libkdeinit5_onboard'
Could not open onboard using a library: Cannot load library libkdeinit5_onboard: (libkdeinit5_onboard: no se puede abrir el fichero del objeto compartido: No existe el fichero o el directorio)
15:12:37.434 WARNING Config: mousetweaks GSettings schema not found, mousetweaks integration disabled.
kdeinit5: Got EXEC_NEW 'alacritty' from launcher.
kdeinit5: preparing to launch 'libkdeinit5_alacritty'
Could not open alacritty using a library: Cannot load library libkdeinit5_alacritty: (libkdeinit5_alacritty: no se puede abrir el fichero del objeto compartido: No existe el fichero o el directorio)
kdeinit5: PID 20342 terminated.
kdeinit5: Got EXEC_NEW 'alacritty' from launcher.
kdeinit5: preparing to launch 'libkdeinit5_alacritty'
Could not open alacritty using a library: Cannot load library libkdeinit5_alacritty: (libkdeinit5_alacritty: no se puede abrir el fichero del objeto compartido: No existe el fichero o el directorio)
kdeinit5: PID 23601 terminated.
kdeinit5: PID 20316 terminated.
kdeinit5: Got EXEC_NEW 'onboard' from launcher.
kdeinit5: preparing to launch 'libkdeinit5_onboard'
Could not open onboard using a library: Cannot load library libkdeinit5_onboard: (libkdeinit5_onboard: no se puede abrir el fichero del objeto compartido: No existe el fichero o el directorio)
15:17:00.192 WARNING Config: mousetweaks GSettings schema not found, mousetweaks integration disabled.
kdeinit5: PID 25051 terminated.
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
2021-01-14 15:18:05,906 [    461]   WARN - llij.ide.plugins.PluginManager - Resource bundle redefinition for plugin 'com.jetbrains.pycharm.community.customization'. Old value: messages.ActionsBundle, new value: messages.PyBundle 
2021-01-14 15:18:07,983 [   2538]   WARN - nSystem.impl.ActionManagerImpl - keymap "Visual Studio" not found [Plugin: com.intellij] 
2021-01-14 15:18:07,986 [   2541]   WARN - nSystem.impl.ActionManagerImpl - keymap "Eclipse" not found [Plugin: com.intellij] 
2021-01-14 15:18:07,986 [   2541]   WARN - nSystem.impl.ActionManagerImpl - keymap "NetBeans 6.5" not found [Plugin: com.intellij] 
2021-01-14 15:18:07,986 [   2541]   WARN - nSystem.impl.ActionManagerImpl - keymap "Visual Studio" not found [Plugin: com.intellij] 
2021-01-14 15:18:08,530 [   3085]   WARN - nSystem.impl.ActionManagerImpl - keymap "Eclipse" not found [Plugin: PythonCore] 
2021-01-14 15:18:08,530 [   3085]   WARN - nSystem.impl.ActionManagerImpl - keymap "NetBeans 6.5" not found [Plugin: PythonCore] 
2021-01-14 15:18:14,032 [   8587]   WARN - openapi.wm.impl.ToolWindowImpl - ToolWindow icons should be 13x13. Please fix ToolWindow (ID:  Problems View) or icon jar:file:/home/govi/Programas/Pycharm/lib/icons.jar!/general/warning.svg 
2021-01-14 15:18:21,868 [  16423]   WARN - .skeletons.PySkeletonRefresher - Some skeletons failed to generate 
2021-01-14 15:18:21,869 [  16424]   WARN - .skeletons.PySkeletonRefresher - PyQt5.QtBluetooth 
2021-01-14 15:18:21,869 [  16424]   WARN - .skeletons.PySkeletonRefresher - PyQt5.QtNetworkAuth 
2021-01-14 15:18:21,869 [  16424]   WARN - .skeletons.PySkeletonRefresher - PyQt5.QtNfc 
2021-01-14 15:18:21,869 [  16424]   WARN - .skeletons.PySkeletonRefresher - PyQt5.QtQuick3D 
2021-01-14 15:18:21,869 [  16424]   WARN - .skeletons.PySkeletonRefresher - PyQt5.QtRemoteObjects 
2021-01-14 15:18:21,869 [  16424]   WARN - .skeletons.PySkeletonRefresher - PyQt5.QtSerialPort 
2021-01-14 15:18:21,869 [  16424]   WARN - .skeletons.PySkeletonRefresher - PyQt5.QtWebSockets 
2021-01-14 15:18:21,869 [  16424]   WARN - .skeletons.PySkeletonRefresher - PyQt5.QtXmlPatterns 
2021-01-14 15:18:21,869 [  16424]   WARN - .skeletons.PySkeletonRefresher - _decimal 
2021-01-14 15:18:21,869 [  16424]   WARN - .skeletons.PySkeletonRefresher - boost.mpi 
2021-01-14 15:18:21,869 [  16424]   WARN - .skeletons.PySkeletonRefresher - cephfs 
2021-01-14 15:18:21,869 [  16424]   WARN - .skeletons.PySkeletonRefresher - imathnumpy 
2021-01-14 15:18:21,869 [  16424]   WARN - .skeletons.PySkeletonRefresher - imobiledevice 
2021-01-14 15:18:21,869 [  16424]   WARN - .skeletons.PySkeletonRefresher - lirc._client 
2021-01-14 15:18:21,869 [  16424]   WARN - .skeletons.PySkeletonRefresher - rados 
2021-01-14 15:18:21,869 [  16424]   WARN - .skeletons.PySkeletonRefresher - rbd 
2021-01-14 15:18:21,869 [  16424]   WARN - .skeletons.PySkeletonRefresher - rgw 
kdeinit5: Got EXEC_NEW 'onboard' from launcher.
kdeinit5: preparing to launch 'libkdeinit5_onboard'
Could not open onboard using a library: Cannot load library libkdeinit5_onboard: (libkdeinit5_onboard: no se puede abrir el fichero del objeto compartido: No existe el fichero o el directorio)
15:19:31.870 WARNING Config: mousetweaks GSettings schema not found, mousetweaks integration disabled.
Unable to init server: No se pudo conectar: Conexi√≥n rehusada

(timeshift-gtk:27807): Gtk-WARNING **: 15:19:34.578: cannot open display: 
kdeinit5: Got EXEC_NEW 'onboard' from launcher.
kdeinit5: preparing to launch 'libkdeinit5_onboard'
Could not open onboard using a library: Cannot load library libkdeinit5_onboard: (libkdeinit5_onboard: no se puede abrir el fichero del objeto compartido: No existe el fichero o el directorio)
kdeinit5: PID 28157 terminated.
kdeinit5: PID 27833 terminated.
