kdeinit5: preparing to launch '/usr/lib/kf5/klauncher'
kdeinit5: Launched KLauncher, pid = 602, result = 0
kdeinit5: opened connection to :0
kdeinit5: Got SETENV 'GTK_RC_FILES=/etc/gtk/gtkrc:/home/govi/.gtkrc:/home/govi/.config/gtkrc' from launcher.
kdeinit5: Got SETENV 'GTK2_RC_FILES=/etc/gtk-2.0/gtkrc:/home/govi/.gtkrc-2.0:/home/govi/.config/gtkrc-2.0' from launcher.
kdeinit5: Got SETENV 'XCURSOR_THEME=GoVi-Cu' from launcher.
kdeinit5: Got SETENV 'XCURSOR_SIZE=24' from launcher.
kdeinit5: Got SETENV 'SESSION_MANAGER=local/GoVi-PC:@/tmp/.ICE-unix/644,unix/GoVi-PC:/tmp/.ICE-unix/644' from launcher.
kdeinit5: Got SETENV 'SESSION_MANAGER=local/GoVi-PC:@/tmp/.ICE-unix/644,unix/GoVi-PC:/tmp/.ICE-unix/644' from launcher.
imwheel: no process found
INFO: imwheel started (pid=910)
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/desktop.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/desktop.so'
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/file.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/file.so'
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/file.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/file.so'
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/file.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/file.so'
kdeinit5: Got EXEC_NEW 'alacritty' from launcher.
kdeinit5: preparing to launch 'libkdeinit5_alacritty'
Could not open alacritty using a library: Cannot load library libkdeinit5_alacritty: (libkdeinit5_alacritty: no se puede abrir el fichero del objeto compartido: No existe el fichero o el directorio)
kdeinit5: PID 1637 terminated.
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/file.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/file.so'
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/file.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/file.so'
kdeinit5: Got EXEC_NEW 'onboard' from launcher.
kdeinit5: preparing to launch 'libkdeinit5_onboard'
Could not open onboard using a library: Cannot load library libkdeinit5_onboard: (libkdeinit5_onboard: no se puede abrir el fichero del objeto compartido: No existe el fichero o el directorio)
21:59:15.686 WARNING Config: mousetweaks GSettings schema not found, mousetweaks integration disabled.
kdeinit5: PID 1370 terminated.
kdeinit5: PID 1063 terminated.
kdeinit5: PID 1266 terminated.
kdeinit5: PID 959 terminated.
[Child 1255, MediaDecoderStateMachine #1] WARNING: Decoder=7f31bf892c00 Decode error: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005) - RefPtr<MediaSourceTrackDemuxer::SamplesPromise> mozilla::MediaSourceTrackDemuxer::DoGetSamples(int32_t): manager is detached.: file /build/firefox/src/firefox-84.0.2/dom/media/MediaDecoderStateMachine.cpp:3471
[Child 1255, MediaDecoderStateMachine #1] WARNING: Decoder=7f31bf892c00 Decode error: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005) - RefPtr<MediaSourceTrackDemuxer::SamplesPromise> mozilla::MediaSourceTrackDemuxer::DoGetSamples(int32_t): manager is detached.: file /build/firefox/src/firefox-84.0.2/dom/media/MediaDecoderStateMachine.cpp:3471
[Child 1255, MediaDecoderStateMachine #1] WARNING: Decoder=7f31bf892c00 Decode error: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005) - RefPtr<MediaSourceTrackDemuxer::SamplesPromise> mozilla::MediaSourceTrackDemuxer::DoGetSamples(int32_t): manager is detached.: file /build/firefox/src/firefox-84.0.2/dom/media/MediaDecoderStateMachine.cpp:3471
[Child 1255, MediaDecoderStateMachine #1] WARNING: Decoder=7f31bf892c00 Decode error: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005) - RefPtr<MediaSourceTrackDemuxer::SamplesPromise> mozilla::MediaSourceTrackDemuxer::DoGetSamples(int32_t): manager is detached.: file /build/firefox/src/firefox-84.0.2/dom/media/MediaDecoderStateMachine.cpp:3471
[Child 1255, MediaDecoderStateMachine #1] WARNING: Decoder=7f31bf892c00 Decode error: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005) - RefPtr<MediaSourceTrackDemuxer::SamplesPromise> mozilla::MediaSourceTrackDemuxer::DoGetSamples(int32_t): manager is detached.: file /build/firefox/src/firefox-84.0.2/dom/media/MediaDecoderStateMachine.cpp:3471
[Child 1255, MediaDecoderStateMachine #1] WARNING: Decoder=7f31bf892c00 Decode error: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005) - RefPtr<MediaSourceTrackDemuxer::SamplesPromise> mozilla::MediaSourceTrackDemuxer::DoGetSamples(int32_t): manager is detached.: file /build/firefox/src/firefox-84.0.2/dom/media/MediaDecoderStateMachine.cpp:3471
[Child 1255, MediaDecoderStateMachine #1] WARNING: Decoder=7f31bf892c00 Decode error: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005) - RefPtr<MediaSourceTrackDemuxer::SamplesPromise> mozilla::MediaSourceTrackDemuxer::DoGetSamples(int32_t): manager is detached.: file /build/firefox/src/firefox-84.0.2/dom/media/MediaDecoderStateMachine.cpp:3471
[Child 1255, MediaDecoderStateMachine #1] WARNING: Decoder=7f31bf892c00 Decode error: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005) - RefPtr<MediaSourceTrackDemuxer::SamplesPromise> mozilla::MediaSourceTrackDemuxer::DoGetSamples(int32_t): manager is detached.: file /build/firefox/src/firefox-84.0.2/dom/media/MediaDecoderStateMachine.cpp:3471
[Child 1255, MediaDecoderStateMachine #1] WARNING: Decoder=7f31bf892c00 Decode error: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005) - RefPtr<MediaSourceTrackDemuxer::SamplesPromise> mozilla::MediaSourceTrackDemuxer::DoGetSamples(int32_t): manager is detached.: file /build/firefox/src/firefox-84.0.2/dom/media/MediaDecoderStateMachine.cpp:3471
[Child 1255, MediaDecoderStateMachine #1] WARNING: Decoder=7f31bf892c00 Decode error: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005) - RefPtr<MediaSourceTrackDemuxer::SamplesPromise> mozilla::MediaSourceTrackDemuxer::DoGetSamples(int32_t): manager is detached.: file /build/firefox/src/firefox-84.0.2/dom/media/MediaDecoderStateMachine.cpp:3471
[Child 1255, MediaDecoderStateMachine #1] WARNING: Decoder=7f31bf892c00 Decode error: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005) - RefPtr<MediaSourceTrackDemuxer::SamplesPromise> mozilla::MediaSourceTrackDemuxer::DoGetSamples(int32_t): manager is detached.: file /build/firefox/src/firefox-84.0.2/dom/media/MediaDecoderStateMachine.cpp:3471
[Child 1255, MediaDecoderStateMachine #1] WARNING: Decoder=7f31bf892c00 Decode error: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005) - RefPtr<MediaSourceTrackDemuxer::SamplesPromise> mozilla::MediaSourceTrackDemuxer::DoGetSamples(int32_t): manager is detached.: file /build/firefox/src/firefox-84.0.2/dom/media/MediaDecoderStateMachine.cpp:3471
[Child 1255, MediaDecoderStateMachine #1] WARNING: Decoder=7f31bf892c00 Decode error: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005) - RefPtr<MediaSourceTrackDemuxer::SamplesPromise> mozilla::MediaSourceTrackDemuxer::DoGetSamples(int32_t): manager is detached.: file /build/firefox/src/firefox-84.0.2/dom/media/MediaDecoderStateMachine.cpp:3471
[Child 1255, MediaDecoderStateMachine #1] WARNING: Decoder=7f31bf892c00 Decode error: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005) - RefPtr<MediaSourceTrackDemuxer::SamplesPromise> mozilla::MediaSourceTrackDemuxer::DoGetSamples(int32_t): manager is detached.: file /build/firefox/src/firefox-84.0.2/dom/media/MediaDecoderStateMachine.cpp:3471
[Child 1255, MediaDecoderStateMachine #1] WARNING: Decoder=7f31bf892c00 Decode error: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005) - RefPtr<MediaSourceTrackDemuxer::SamplesPromise> mozilla::MediaSourceTrackDemuxer::DoGetSamples(int32_t): manager is detached.: file /build/firefox/src/firefox-84.0.2/dom/media/MediaDecoderStateMachine.cpp:3471
[Child 1255, MediaDecoderStateMachine #1] WARNING: Decoder=7f31bf892c00 Decode error: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005) - RefPtr<MediaSourceTrackDemuxer::SamplesPromise> mozilla::MediaSourceTrackDemuxer::DoGetSamples(int32_t): manager is detached.: file /build/firefox/src/firefox-84.0.2/dom/media/MediaDecoderStateMachine.cpp:3471
[Child 1255, MediaDecoderStateMachine #1] WARNING: Decoder=7f31bf892c00 Decode error: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005) - RefPtr<MediaSourceTrackDemuxer::SamplesPromise> mozilla::MediaSourceTrackDemuxer::DoGetSamples(int32_t): manager is detached.: file /build/firefox/src/firefox-84.0.2/dom/media/MediaDecoderStateMachine.cpp:3471
[Child 1255, MediaDecoderStateMachine #1] WARNING: Decoder=7f31bf892c00 Decode error: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005) - RefPtr<MediaSourceTrackDemuxer::SamplesPromise> mozilla::MediaSourceTrackDemuxer::DoGetSamples(int32_t): manager is detached.: file /build/firefox/src/firefox-84.0.2/dom/media/MediaDecoderStateMachine.cpp:3471
[Child 1255, MediaDecoderStateMachine #1] WARNING: Decoder=7f31bf892c00 Decode error: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005) - RefPtr<MediaSourceTrackDemuxer::SamplesPromise> mozilla::MediaSourceTrackDemuxer::DoGetSamples(int32_t): manager is detached.: file /build/firefox/src/firefox-84.0.2/dom/media/MediaDecoderStateMachine.cpp:3471
[Child 1255, MediaDecoderStateMachine #1] WARNING: Decoder=7f31bf892c00 Decode error: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005) - RefPtr<MediaSourceTrackDemuxer::SamplesPromise> mozilla::MediaSourceTrackDemuxer::DoGetSamples(int32_t): manager is detached.: file /build/firefox/src/firefox-84.0.2/dom/media/MediaDecoderStateMachine.cpp:3471
[Child 1255, MediaDecoderStateMachine #1] WARNING: Decoder=7f31bf892c00 Decode error: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005) - RefPtr<MediaSourceTrackDemuxer::SamplesPromise> mozilla::MediaSourceTrackDemuxer::DoGetSamples(int32_t): manager is detached.: file /build/firefox/src/firefox-84.0.2/dom/media/MediaDecoderStateMachine.cpp:3471
[Child 1255, MediaDecoderStateMachine #1] WARNING: Decoder=7f31bf892c00 Decode error: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005) - RefPtr<MediaSourceTrackDemuxer::SamplesPromise> mozilla::MediaSourceTrackDemuxer::DoGetSamples(int32_t): manager is detached.: file /build/firefox/src/firefox-84.0.2/dom/media/MediaDecoderStateMachine.cpp:3471
[Child 1255, MediaDecoderStateMachine #1] WARNING: Decoder=7f31bf892c00 Decode error: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005) - RefPtr<MediaSourceTrackDemuxer::SamplesPromise> mozilla::MediaSourceTrackDemuxer::DoGetSamples(int32_t): manager is detached.: file /build/firefox/src/firefox-84.0.2/dom/media/MediaDecoderStateMachine.cpp:3471
[Child 1255, MediaDecoderStateMachine #1] WARNING: Decoder=7f31bf892c00 Decode error: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005) - RefPtr<MediaSourceTrackDemuxer::SamplesPromise> mozilla::MediaSourceTrackDemuxer::DoGetSamples(int32_t): manager is detached.: file /build/firefox/src/firefox-84.0.2/dom/media/MediaDecoderStateMachine.cpp:3471
[Child 1255, MediaDecoderStateMachine #1] WARNING: Decoder=7f31bf892c00 Decode error: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005) - RefPtr<MediaSourceTrackDemuxer::SamplesPromise> mozilla::MediaSourceTrackDemuxer::DoGetSamples(int32_t): manager is detached.: file /build/firefox/src/firefox-84.0.2/dom/media/MediaDecoderStateMachine.cpp:3471
[Child 1255, MediaDecoderStateMachine #1] WARNING: Decoder=7f31bf892c00 Decode error: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005) - RefPtr<MediaSourceTrackDemuxer::SamplesPromise> mozilla::MediaSourceTrackDemuxer::DoGetSamples(int32_t): manager is detached.: file /build/firefox/src/firefox-84.0.2/dom/media/MediaDecoderStateMachine.cpp:3471
kdeinit5: Got EXEC_NEW 'onboard' from launcher.
kdeinit5: preparing to launch 'libkdeinit5_onboard'
Could not open onboard using a library: Cannot load library libkdeinit5_onboard: (libkdeinit5_onboard: no se puede abrir el fichero del objeto compartido: No existe el fichero o el directorio)
WINDOW DECORATIONS RELOADED
kdeinit5: PID 8284 terminated.
KCrash: crashing... crashRecursionCounter = 2
KCrash: Application Name = kmenuedit path = /usr/bin pid = 2271
KCrash: Arguments: /usr/bin/kmenuedit 
KCrash: Attempting to start /usr/lib/drkonqi
kdeinit5: Got EXEC_NEW '/usr/bin/kmenuedit' from launcher.
kdeinit5: preparing to launch '/usr/bin/kmenuedit'
WINDOW DECORATIONS RELOADED
kdeinit5: PID 3123 terminated.
Unable to start Dr. Konqi
Re-raising signal for core dump handling.
kdeinit5: Got EXEC_NEW 'onboard' from launcher.
kdeinit5: preparing to launch 'libkdeinit5_onboard'
Could not open onboard using a library: Cannot load library libkdeinit5_onboard: (libkdeinit5_onboard: no se puede abrir el fichero del objeto compartido: No existe el fichero o el directorio)
22:06:31.860 WARNING Config: mousetweaks GSettings schema not found, mousetweaks integration disabled.
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/tags.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/tags.so'
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/trash.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/trash.so'
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/file.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/file.so'
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/file.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/file.so'
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/file.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/file.so'
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/thumbnail.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/thumbnail.so'
kdeinit5: PID 12127 terminated.
kdeinit5: PID 12131 terminated.
kdeinit5: PID 12130 terminated.
kdeinit5: PID 12125 terminated.
kdeinit5: PID 12126 terminated.
kdeinit5: PID 12133 terminated.
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/tags.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/tags.so'
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/trash.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/trash.so'
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/file.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/file.so'
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/file.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/file.so'
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/file.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/file.so'
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/thumbnail.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/thumbnail.so'
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/file.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/file.so'
kdeinit5: PID 13089 terminated.
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/tags.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/tags.so'
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/file.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/file.so'
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/thumbnail.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/thumbnail.so'
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/file.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/file.so'
kdeinit5: PID 13085 terminated.
kdeinit5: PID 13088 terminated.
kdeinit5: PID 13084 terminated.
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/thumbnail.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/thumbnail.so'
kdeinit5: PID 16743 terminated.
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/thumbnail.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/thumbnail.so'
kdeinit5: PID 17311 terminated.
kdeinit5: PID 13137 terminated.
kdeinit5: PID 13083 terminated.
kdeinit5: PID 13106 terminated.
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
sudo: a password is required
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
sudo: a password is required
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
sudo: a password is required
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
kdeinit5: PID 16845 terminated.
kdeinit5: PID 16740 terminated.
kdeinit5: PID 16739 terminated.
kdeinit5: PID 17353 terminated.
kdeinit5: PID 8869 terminated.
sudo: a password is required
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
sudo: a password is required
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
sudo: a password is required
rm: no se puede borrar '/home/govi/.cache/vim': Permiso denegado
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/file.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/file.so'
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/thumbnail.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/thumbnail.so'
kdeinit5: PID 19512 terminated.
kdeinit5: PID 19539 terminated.
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/tags.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/tags.so'
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/trash.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/trash.so'
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/file.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/file.so'
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/file.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/file.so'
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/file.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/file.so'
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/thumbnail.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/thumbnail.so'
kdeinit5: PID 20629 terminated.
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/thumbnail.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/thumbnail.so'
kdeinit5: Got EXEC_NEW 'onboard' from launcher.
kdeinit5: preparing to launch 'libkdeinit5_onboard'
Could not open onboard using a library: Cannot load library libkdeinit5_onboard: (libkdeinit5_onboard: no se puede abrir el fichero del objeto compartido: No existe el fichero o el directorio)
WINDOW DECORATIONS RELOADED
kdeinit5: PID 21763 terminated.
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/tags.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/tags.so'
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/file.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/file.so'
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/thumbnail.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/thumbnail.so'
kdeinit5: PID 20616 terminated.
kdeinit5: PID 20619 terminated.
kdeinit5: PID 20615 terminated.
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/file.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/file.so'
kdeinit5: PID 25002 terminated.
kdeinit5: PID 25001 terminated.
kdeinit5: PID 25449 terminated.
kdeinit5: PID 25007 terminated.
kdeinit5: PID 20614 terminated.
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/tags.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/tags.so'
Failed to start teamviewerd.service: Access denied
See system logs and 'systemctl status teamviewerd.service' for details.
Failed to stop teamviewerd.service: Access denied
See system logs and 'systemctl status teamviewerd.service' for details.
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/desktop.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/desktop.so'
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/file.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/file.so'
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/file.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/file.so'
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/file.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/file.so'
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/file.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/file.so'
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/tags.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/tags.so'
kdeinit5: PID 33416 terminated.
kdeinit5: PID 20620 terminated.
kdeinit5: PID 29919 terminated.
kdeinit5: PID 33417 terminated.
kdeinit5: PID 21428 terminated.
WINDOW DECORATIONS RELOADED
kdeinit5: PID 10340 terminated.
kdeinit5: Got EXEC_NEW 'onboard' from launcher.
kdeinit5: preparing to launch 'libkdeinit5_onboard'
Could not open onboard using a library: Cannot load library libkdeinit5_onboard: (libkdeinit5_onboard: no se puede abrir el fichero del objeto compartido: No existe el fichero o el directorio)
22:32:03.974 WARNING Config: mousetweaks GSettings schema not found, mousetweaks integration disabled.
kdeinit5: PID 32650 terminated.
WINDOW DECORATIONS RELOADED
kdeinit5: PID 35313 terminated.
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/tags.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/tags.so'
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/trash.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/trash.so'
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/file.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/file.so'
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/file.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/file.so'
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/file.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/file.so'
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/thumbnail.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/thumbnail.so'
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/file.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/file.so'
kdeinit5: PID 36165 terminated.
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/thumbnail.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/thumbnail.so'
kdeinit5: PID 36171 terminated.
kdeinit5: PID 36168 terminated.
rm: fts_read falló: No existe el fichero o el directorio
kdeinit5: PID 33720 terminated.
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/tinyMediaManager/templates/DeadSix27HTMLGeneratorTV/template.conf': El fichero ya existe
cp: no se puede crear el directorio '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/tinyMediaManager/templates/ListExampleHtml': El fichero ya existe
cp: no se puede crear el directorio '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/tinyMediaManager/templates/ListExampleCsv': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/tinyMediaManager/templates/templates.jar': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/tinyMediaManager/lib/glazedlists.jar': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/tinyMediaManager/lib/commons-io.jar': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/tinyMediaManager/lib/asm.jar': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/tinyMediaManager/lib/thetvdb-java.jar': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/tinyMediaManager/lib/okhttp.jar': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/tinyMediaManager/gettingdown.lock': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/tinyMediaManager/digest.txt': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/tinyMediaManager/getdown.jar': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/tinyMediaManager/env.txt': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/tinyMediaManager/tmm.jar': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/ReNamer/App/ReNamer/Languages/ReNamer.tr_2.po': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/ReNamer/App/ReNamer/Languages/ReNamer.ta.po': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/ReNamer/App/ReNamer/Languages/ReNamer.zh_CN.po': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/ReNamer/App/ReNamer/Languages/ReNamer.uk.po': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/ReNamer/App/ReNamer/Languages/ReNamer.sr.po': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/ReNamer/App/ReNamer/Help/Quick Guide.pdf': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/ReNamer/App/ReNamer/ReNamer.exe': El fichero ya existe
cp: no se puede crear el directorio '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/locale/af': El fichero ya existe
cp: no se puede crear el directorio '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/locale/ja': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/locale/eo/LC_MESSAGES/picard.mo': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/locale/eo/LC_MESSAGES/picard-attributes.mo': El fichero ya existe
cp: no se puede crear el directorio '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/locale/zh_CN': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/locale/zh/LC_MESSAGES/picard-countries.mo': El fichero ya existe
cp: no se puede crear el directorio '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/locale/kn': El fichero ya existe
cp: no se puede crear el directorio '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/locale/hu': El fichero ya existe
cp: no se puede crear el directorio '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/locale/en_GB': El fichero ya existe
cp: no se puede crear el directorio '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/locale/vi': El fichero ya existe
cp: no se puede crear el directorio '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/locale/nb': El fichero ya existe
cp: no se puede crear el directorio '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/locale/pa': El fichero ya existe
cp: no se puede crear el directorio '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/locale/ca': El fichero ya existe
cp: no se puede crear el directorio '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/locale/oc': El fichero ya existe
cp: no se puede crear el directorio '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/locale/nl_BE': El fichero ya existe
cp: no se puede crear el directorio '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/locale/pt_BR': El fichero ya existe
cp: no se puede crear el directorio '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/locale/zh_TW': El fichero ya existe
cp: no se puede crear el directorio '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/locale/de_CH': El fichero ya existe
cp: no se puede crear el directorio '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/locale/ast': El fichero ya existe
cp: no se puede crear el directorio '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/locale/et': El fichero ya existe
cp: no se puede crear el directorio '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/locale/fr_CA': El fichero ya existe
cp: no se puede crear el directorio '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/locale/en_CA': El fichero ya existe
cp: no se puede crear el directorio '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/locale/bg': El fichero ya existe
cp: no se puede crear el directorio '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/locale/en_AU': El fichero ya existe
cp: no se puede crear el directorio '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/locale/fo': El fichero ya existe
cp: no se puede crear el directorio '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/locale/cs': El fichero ya existe
cp: no se puede crear el directorio '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/locale/fr': El fichero ya existe
cp: no se puede crear el directorio '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/locale/de': El fichero ya existe
cp: no se puede crear el directorio '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/locale/ko': El fichero ya existe
cp: no se puede crear el directorio '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/locale/sl': El fichero ya existe
cp: no se puede crear el directorio '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/locale/ar': El fichero ya existe
cp: no se puede crear el directorio '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/locale/es': El fichero ya existe
cp: no se puede crear el directorio '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/locale/pt_PT': El fichero ya existe
cp: no se puede crear el directorio '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/locale/sq': El fichero ya existe
cp: no se puede crear el directorio '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/locale/es_419': El fichero ya existe
cp: no se puede crear el directorio '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/locale/uk': El fichero ya existe
cp: no se puede crear el directorio '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/locale/lt': El fichero ya existe
cp: no se puede crear el directorio '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/locale/mr': El fichero ya existe
cp: no se puede crear el directorio '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/locale/el': El fichero ya existe
cp: no se puede crear el directorio '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/locale/ru': El fichero ya existe
cp: no se puede crear el directorio '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/locale/ro': El fichero ya existe
cp: no se puede crear el directorio '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/locale/fi': El fichero ya existe
cp: no se puede crear el directorio '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/PyQt5': El fichero ya existe
cp: no se puede crear el directorio '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/picard': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/MSVCP140.dll': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/api-ms-win-core-heap-l1-1-0.dll': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/Qt5WebSockets.dll': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/api-ms-win-core-file-l2-1-0.dll': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/api-ms-win-crt-process-l1-1-0.dll': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/api-ms-win-core-localization-l1-2-0.dll': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/api-ms-win-core-handle-l1-1-0.dll': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/picard.exe.manifest': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/Square70x70Logo.png': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/api-ms-win-core-file-l1-2-0.dll': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/api-ms-win-core-processthreads-l1-1-0.dll': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/_decimal.pyd': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/api-ms-win-crt-utility-l1-1-0.dll': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/api-ms-win-core-util-l1-1-0.dll': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/_ctypes.pyd': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/api-ms-win-crt-conio-l1-1-0.dll': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/api-ms-win-core-winrt-l1-1-0.dll': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/Qt5Quick.dll': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/api-ms-win-core-libraryloader-l1-1-0.dll': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/api-ms-win-core-errorhandling-l1-1-0.dll': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/ucrtbase.dll': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/api-ms-win-core-debug-l1-1-0.dll': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/api-ms-win-crt-convert-l1-1-0.dll': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/python37.dll': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/_bz2.pyd': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/select.pyd': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/api-ms-win-core-sysinfo-l1-1-0.dll': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/api-ms-win-core-processenvironment-l1-1-0.dll': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/_ssl.pyd': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/uninst.exe': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/Qt5Widgets.dll': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/api-ms-win-crt-runtime-l1-1-0.dll': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/picard.VisualElementsManifest.xml': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/Square44x44Logo.targetsize-44_altform-unplated.png': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/libcrypto-1_1-x64.dll': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/api-ms-win-crt-heap-l1-1-0.dll': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/MusicBrainz Picard.lnk': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/VCRUNTIME140.dll': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/Qt5Gui.dll': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/Square150x150Logo.png': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/Qt5Qml.dll': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/_lzma.pyd': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/Qt5WinExtras.dll': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/unicodedata.pyd': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard/base_library.zip': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/MusicBrainz Picard.lnk': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/ReNamer.lnk': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/Kodi Texture Tool.lnk': El fichero ya existe
cp: no se puede crear el fichero regular '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Utils/tinyMediaManager.lnk': El fichero ya existe
cp: no se puede crear el directorio '/home/govi/Backups/Kodi/Backups/Builds/Current/.kodi/media/Players': El fichero ya existe
kdeinit5: PID 36169 terminated.
kdeinit5: PID 36246 terminated.
kdeinit5: PID 36162 terminated.
kdeinit5: PID 36164 terminated.
kdeinit5: PID 36341 terminated.
kdeinit5: PID 32647 terminated.
kdeinit5: PID 32649 terminated.
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/desktop.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/desktop.so'
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/file.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/file.so'
mv: no se puede efectuar `stat' sobre '/home/govi/Escritorio/Kodi-GoVi_Build.zip': No existe el fichero o el directorio
kdeinit5: Got EXEC_NEW 'onboard' from launcher.
kdeinit5: preparing to launch 'libkdeinit5_onboard'
Could not open onboard using a library: Cannot load library libkdeinit5_onboard: (libkdeinit5_onboard: no se puede abrir el fichero del objeto compartido: No existe el fichero o el directorio)
22:36:15.534 WARNING Config: mousetweaks GSettings schema not found, mousetweaks integration disabled.
kdeinit5: PID 37366 terminated.
kdeinit5: PID 37364 terminated.
WINDOW DECORATIONS RELOADED
kdeinit5: PID 39384 terminated.
kdeinit5: Got EXEC_NEW 'onboard' from launcher.
kdeinit5: preparing to launch 'libkdeinit5_onboard'
Could not open onboard using a library: Cannot load library libkdeinit5_onboard: (libkdeinit5_onboard: no se puede abrir el fichero del objeto compartido: No existe el fichero o el directorio)
22:41:46.355 WARNING Config: mousetweaks GSettings schema not found, mousetweaks integration disabled.
WINDOW DECORATIONS RELOADED
kdeinit5: PID 44592 terminated.
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/tags.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/tags.so'
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/trash.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/trash.so'
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/file.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/file.so'
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/file.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/file.so'
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/file.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/file.so'
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/thumbnail.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/thumbnail.so'
[Child 1255, MediaDecoderStateMachine #1] WARNING: Decoder=7f31a8905c00 Decode error: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005) - RefPtr<MediaSourceTrackDemuxer::SamplesPromise> mozilla::MediaSourceTrackDemuxer::DoGetSamples(int32_t): manager is detached.: file /build/firefox/src/firefox-84.0.2/dom/media/MediaDecoderStateMachine.cpp:3471
[Child 1255, MediaDecoderStateMachine #1] WARNING: Decoder=7f31a8905c00 Decode error: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005) - RefPtr<MediaSourceTrackDemuxer::SamplesPromise> mozilla::MediaSourceTrackDemuxer::DoGetSamples(int32_t): manager is detached.: file /build/firefox/src/firefox-84.0.2/dom/media/MediaDecoderStateMachine.cpp:3471
[Child 1255, MediaDecoderStateMachine #1] WARNING: Decoder=7f31a8905c00 Decode error: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005) - RefPtr<MediaSourceTrackDemuxer::SamplesPromise> mozilla::MediaSourceTrackDemuxer::DoGetSamples(int32_t): manager is detached.: file /build/firefox/src/firefox-84.0.2/dom/media/MediaDecoderStateMachine.cpp:3471
[Child 1255, MediaDecoderStateMachine #1] WARNING: Decoder=7f31a8905c00 Decode error: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005) - RefPtr<MediaSourceTrackDemuxer::SamplesPromise> mozilla::MediaSourceTrackDemuxer::DoGetSamples(int32_t): manager is detached.: file /build/firefox/src/firefox-84.0.2/dom/media/MediaDecoderStateMachine.cpp:3471
[Child 1255, MediaDecoderStateMachine #1] WARNING: Decoder=7f31a8905c00 Decode error: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005) - RefPtr<MediaSourceTrackDemuxer::SamplesPromise> mozilla::MediaSourceTrackDemuxer::DoGetSamples(int32_t): manager is detached.: file /build/firefox/src/firefox-84.0.2/dom/media/MediaDecoderStateMachine.cpp:3471
[Child 1255, MediaDecoderStateMachine #1] WARNING: Decoder=7f31a8905c00 Decode error: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005) - RefPtr<MediaSourceTrackDemuxer::SamplesPromise> mozilla::MediaSourceTrackDemuxer::DoGetSamples(int32_t): manager is detached.: file /build/firefox/src/firefox-84.0.2/dom/media/MediaDecoderStateMachine.cpp:3471
[Child 1255, MediaDecoderStateMachine #1] WARNING: Decoder=7f31a8905c00 Decode error: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005) - RefPtr<MediaSourceTrackDemuxer::SamplesPromise> mozilla::MediaSourceTrackDemuxer::DoGetSamples(int32_t): manager is detached.: file /build/firefox/src/firefox-84.0.2/dom/media/MediaDecoderStateMachine.cpp:3471
[Child 1255, MediaDecoderStateMachine #1] WARNING: Decoder=7f31a8905c00 Decode error: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005) - RefPtr<MediaSourceTrackDemuxer::SamplesPromise> mozilla::MediaSourceTrackDemuxer::DoGetSamples(int32_t): manager is detached.: file /build/firefox/src/firefox-84.0.2/dom/media/MediaDecoderStateMachine.cpp:3471
kdeinit5: Got EXEC_NEW 'onboard' from launcher.
kdeinit5: preparing to launch 'libkdeinit5_onboard'
Could not open onboard using a library: Cannot load library libkdeinit5_onboard: (libkdeinit5_onboard: no se puede abrir el fichero del objeto compartido: No existe el fichero o el directorio)
22:43:34.099 WARNING Config: mousetweaks GSettings schema not found, mousetweaks integration disabled.
kdeinit5: PID 45688 terminated.
kdeinit5: PID 45694 terminated.
kdeinit5: PID 45697 terminated.
kdeinit5: PID 45689 terminated.
kdeinit5: PID 45705 terminated.
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/thumbnail.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/thumbnail.so'
kdeinit5: PID 45698 terminated.
kdeinit5: PID 52413 terminated.
WINDOW DECORATIONS RELOADED
kdeinit5: PID 46559 terminated.

(liferea:52852): libsecret-CRITICAL **: 22:50:02.359: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.360: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.361: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.362: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.363: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.364: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.364: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.365: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.368: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.370: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.372: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.373: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.375: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.376: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.377: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.379: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.380: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.382: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.383: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.385: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.386: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.387: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.388: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.389: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.391: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.392: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.393: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.397: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.399: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.400: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.401: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.403: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.404: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.405: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.407: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.408: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.409: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.411: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.412: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.413: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.415: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.416: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.417: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.418: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.420: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.421: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.422: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.424: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.425: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.426: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.428: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.430: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.432: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.434: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.435: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.436: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.437: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.439: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.440: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.441: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.442: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.443: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.444: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.447: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.449: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.450: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.451: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.452: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.453: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.454: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.454: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.455: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.456: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.458: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.459: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.459: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.460: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.461: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.463: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.464: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.465: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.466: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.467: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.467: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.468: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.469: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.470: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.471: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.472: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.473: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.474: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.474: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.475: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.476: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.477: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.479: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.480: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.480: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.481: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.482: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.485: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.487: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.488: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.489: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.492: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.494: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.495: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.496: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.497: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.497: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.499: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.500: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.501: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.502: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.502: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.503: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.504: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.505: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.505: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.506: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.507: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.507: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.508: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.508: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.509: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.510: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.512: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.513: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.514: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.515: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.516: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.516: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.517: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'

(liferea:52852): libsecret-CRITICAL **: 22:50:02.517: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'
